fetch_data:
  name: Fetch data
  description: Refresh data for the selected wallbox.
  target:
    device:
      integration: integration_keba_rest_api

start_charging:
  name: Start charging
  description: Start charging for the selected wallbox.
  target:
    device:
      integration: integration_keba_rest_api

stop_charging:
  name: Stop charging
  description: Stop charging for the selected wallbox.
  target:
    device:
      integration: integration_keba_rest_api
