#!/usr/bin/env python3
"""Synchronize and index the KEBA REST API OpenAPI document."""

from __future__ import annotations

import argparse
import json
import os
import ssl
import sys
import tempfile
from pathlib import Path
from urllib.error import URLError
from urllib.request import Request, urlopen


URL_ENV_VAR = "KEBA_OPENAPI_URL"
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent
USER_AGENT = "homeassistant-keba-rest-api-openapi-sync/1.0"


def _load_dotenv(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("\"'"))


def _download(url: str, timeout: int) -> dict:
    request = Request(url, headers={"User-Agent": USER_AGENT})
    context = ssl.create_default_context()
    try:
        with urlopen(request, timeout=timeout, context=context) as response:
            payload = response.read()
    except URLError as exc:
        raise RuntimeError(f"Unable to download OpenAPI document: {exc}") from exc

    try:
        document = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise RuntimeError("Downloaded OpenAPI document is not valid JSON") from exc

    _validate_document(document)
    return document


def _load_snapshot(path: Path) -> dict:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"Unable to load local snapshot {path}: {exc}") from exc
    _validate_document(document)
    return document


def _validate_document(document: object) -> None:
    if not isinstance(document, dict) or document.get("openapi") != "3.0.3":
        raise RuntimeError("Expected an OpenAPI 3.0.3 document")
    if not isinstance(document.get("info"), dict):
        raise RuntimeError("OpenAPI document has no valid info object")
    if not isinstance(document.get("paths"), dict) or not document["paths"]:
        raise RuntimeError("OpenAPI document has no paths")


def _write_json(path: Path, document: dict) -> None:
    path.write_text(
        json.dumps(document, ensure_ascii=True, indent=2) + "\n",
        encoding="utf-8",
    )


def _operation_rows(document: dict) -> list[tuple[str, str, dict]]:
    rows = []
    for path, path_item in sorted(document["paths"].items()):
        if not isinstance(path_item, dict):
            continue
        for method, operation in sorted(path_item.items()):
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            if isinstance(operation, dict):
                rows.append((method.upper(), path, operation))
    return rows


def _schema_name(schema: object) -> str:
    if isinstance(schema, dict) and "$ref" in schema:
        return str(schema["$ref"]).removeprefix("#/components/schemas/")
    if isinstance(schema, dict):
        return str(schema.get("title", "inline schema"))
    return "unspecified"


def _response_schemas(operation: dict) -> str:
    responses = operation.get("responses", {})
    if not isinstance(responses, dict):
        return "unspecified"
    values = []
    for status, response in sorted(responses.items()):
        schema = None
        if isinstance(response, dict):
            content = response.get("content", {})
            if isinstance(content, dict):
                for media_type in sorted(content):
                    media = content[media_type]
                    if isinstance(media, dict) and "schema" in media:
                        schema = _schema_name(media["schema"])
                        break
        values.append(f"`{status}`: `{schema or 'no body'}`")
    return "; ".join(values) or "unspecified"


def _write_index(path: Path, document: dict) -> None:
    info = document["info"]
    rows = _operation_rows(document)
    lines = [
        "# KEBA REST API endpoint index",
        "",
        "<!-- Generated by sync_openapi.py. Do not edit manually. -->",
        "",
        f"Source contract version: `{info.get('version', 'unknown')}`  ",
        f"OpenAPI version: `{document['openapi']}`  ",
        f"Operations: `{len(rows)}`  ",
        f"Paths: `{len(document['paths'])}`",
        "",
        "| Method | Path | Tags | Responses |",
        "| --- | --- | --- | --- |",
    ]
    for method, endpoint, operation in rows:
        tags = ", ".join(f"`{tag}`" for tag in operation.get("tags", [])) or "-"
        summary = operation.get("summary", "").replace("|", "\\|")
        label = f"{endpoint} ({summary})" if summary else endpoint
        lines.append(
            f"| `{method}` | `{label}` | {tags} | {_response_schemas(operation)} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_metadata(path: Path, document: dict) -> None:
    schemas = document.get("components", {}).get("schemas", {})
    lines = [
        "# OpenAPI source",
        "",
        "This directory is the Copilot-facing API reference for the integration.",
        "",
        f"The live contract is synchronized from `{URL_ENV_VAR}` in `.env` or the environment.",
        "",
        "Generated files:",
        "- `openapi_orig.json`: synchronized source snapshot",
        "- `openapi_pretty.json`: readable equivalent of the snapshot",
        "- `endpoint_index.md`: complete method/path/response inventory",
        "",
        "The generated files must be refreshed with:",
        "```text",
        "python3 docs/keba-rest-api/sync_openapi.py",
        "```",
        "",
        "The synchronizer uses the existing snapshot only with `--offline`.",
        "It writes files atomically so a failed download cannot replace a valid snapshot.",
        "",
        f"Current contract: OpenAPI `{document['openapi']}`, API version `{document['info'].get('version', 'unknown')}`, `{len(document['paths'])}` paths, `{len(schemas)}` schemas.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _replace_outputs(output_dir: Path, document: dict) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "openapi_orig.json": lambda path: _write_json(path, document),
        "openapi_pretty.json": lambda path: _write_json(path, document),
        "endpoint_index.md": lambda path: _write_index(path, document),
        "README.md": lambda path: _write_metadata(path, document),
    }
    with tempfile.TemporaryDirectory(dir=output_dir) as temporary_dir:
        temporary = Path(temporary_dir)
        for filename, writer in files.items():
            writer(temporary / filename)
        for filename in files:
            (temporary / filename).replace(output_dir / filename)


def main() -> int:
    _load_dotenv(DEFAULT_OUTPUT_DIR / ".env")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--url",
        default=os.environ.get(URL_ENV_VAR),
        help=f"Live OpenAPI URL (defaults to {URL_ENV_VAR})",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for synchronized artifacts",
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help="Use the existing openapi_orig.json instead of downloading",
    )
    parser.add_argument("--timeout", type=int, default=30)
    args = parser.parse_args()

    snapshot = args.output_dir / "openapi_orig.json"
    try:
        if args.offline:
            document = _load_snapshot(snapshot)
        elif not args.url:
            raise RuntimeError(
                f"{URL_ENV_VAR} is not set; configure it in {DEFAULT_OUTPUT_DIR / '.env'} "
                "or pass --url"
            )
        else:
            document = _download(args.url, args.timeout)
        _replace_outputs(args.output_dir, document)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(
        f"Synchronized OpenAPI {document['info'].get('version', 'unknown')}: "
        f"{len(document['paths'])} paths, "
        f"{len(document.get('components', {}).get('schemas', {}))} schemas"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
